language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - build-tools-28.0.3
    - android-23
    - extra-android-m2repository
    - extra-google-m2repository

script:
  - ./gradlew buildDictionaries build
