language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - build-tools-29.0.3
    - android-29
    - extra-android-m2repository

script:
  - ./gradlew buildDictionaries
  - ./gradlew build
  - ./gradlew check
