name: Build dictionaries and app, then run tests

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]

jobs:

  build-and-check:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Gradle build dictionaries
      run: ./gradlew buildDictionaries

    - name: Gradle build
      run: ./gradlew build

    - name: Gradle check
      run: ./gradlew check

